### ISSUE TITLE
Borked descriptions

### ISSUE THREAD

**Issue by satyarth** [Fedjmike/r8music#47]
Wikipedia links work fine, something's getting janked at import time.

**Comment by satyarth** [comment]
cb3e633 unjanked

**Comment by satyarth** [comment]
- [ ]  todo: Update DB

**Comment by Fedjmike** [comment]
https://gist.github.com/Fedjmike/da0cb4296a7462055ba2c9b014858b7c

**Comment by Fedjmike** [comment]
Fixed in django-v2
