### ISSUE TITLE
Update artists

### ISSUE THREAD

**Issue by satyarth** [Fedjmike/r8music#49]
Comes under #14.

Partially implemented in 5c476e0.

Todo:
- [ ] Update external links (changing handles etc.)
- [ ] Update releases (tracklists for releases from before multiple discs were implemented, updates to release types, etc.)
- [x] Fix our shitty `incomplete` system (system didn't account for releases being added after import)
- [ ] Handle cases where the artist's name (hence slug) have been changed. For example, trying to update http://r8music.com/uyama-hiroto creates a new artist with the updated name. _Edit:_ This isn't because the artist name or slug changed, it's because the artist got an entirely new mbid. Can only be solved by merging.

**Comment by satyarth** [comment]
It's simpler for now I guess, but I don't like it in principle. Doing it that way, we'd need to write code to move around things everytime we introduce a new feature.

Other shit to do:
[ ] Fix our shitty `incomplete` system
[ ] Handle cases where the artist's name (hence slug) have been changed. For example, trying to update http://r8music.com/uyama-hiroto creates a new artist with the updated name

**Comment by Fedjmike** [comment]
There already is code to move things around, and it's necessary either way because merging duplicates isn't a feature we can do without. Given it's there, use it for updating.

**Comment by satyarth** [comment]
There is code to move things that exist, code for new features will have to be written. There are no duplicates (as far as I've seen) in the sense you're thinking of (i.e. two pretty much identical entries for the same artist, with user activity on both that need to be merged). The current duplicates just need their artist ids changed on the authorships, links, descriptions tables. We'll have to do all the harder stuff (matching releases that might have changed, etc. anyway), why make our lives harder?

**Comment by Fedjmike** [comment]
So, MAYBE there will never ever be a duplicate again and we won't ever need to write that code.

Even if there isn't, what's so complex? Not sure what you mean about matching: you just check the mbid, or failing that, title etc. There's more than enough data to make a good heuristic for "this is the same release". And the code is already written. What's the complexity?

**Comment by satyarth** [comment]
![seemsgood](https://cloud.githubusercontent.com/assets/5021922/19419471/f541cb50-93e0-11e6-83c0-e157cae96d5b.png)

**Comment by satyarth** [comment]
What happens when something janks up during updating (server restart, etc.)? Would require manual intervention, as opposed to  updating in place where you can just hit update again, no harm done

**Comment by Fedjmike** [comment]
Well if it janks during the second import, no biggie. If it janks during the move: well, just finish the move.

**Comment by Fedjmike** [comment]
Done in django-v2
