### ISSUE TITLE
Infinite scrolling on activity feeds

### ISSUE THREAD

**Issue by Fedjmike** [Fedjmike/r8music#87]

**Comment by satyarth** [comment]
I've basically done it on my `uscroll` branch, just need some minor adjustments (like conditionally loading the JS for it). Would there still be a manual 'load more' button? Could have both I suppose, we might want to integrate feeds on pages we don't want infinite scrolling on but want people to be able to load more stuff.

**Comment by Fedjmike** [comment]
Done with 7200525
