### ISSUE TITLE
"Start with" on artist pages

### ISSUE THREAD

**Issue by Fedjmike** [Fedjmike/r8music#88]
Voted by users? Or calculated? The latter serves no extra purpose than average ratings which are there already. Also, a discrete choice like where to start is easier than rating the albums. Is the selection on each release page (I say no) or in its own section on the artist page (I think so).

**Comment by satyarth** [comment]
Would just presenting say, the three most popular releases not work? (Popular = total listens)

**Comment by Fedjmike** [comment]
Yeah, did that. b4241c0
